apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: frontend
data:
  PORT: "8080"

  PRODUCT_CATALOG_SERVICE_ADDR: productcatalogservice.productcatalog.svc.cluster.local:3550
  CURRENCY_SERVICE_ADDR: currencyservice.currency.svc.cluster.local:7000
  CART_SERVICE_ADDR: cartservice.cartservice.svc.cluster.local:7070
  RECOMMENDATION_SERVICE_ADDR: recommendationservice.recommendation.svc.cluster.local:8080
  SHIPPING_SERVICE_ADDR: shippingservice.shipping.svc.cluster.local:50051
  CHECKOUT_SERVICE_ADDR: checkoutservice.checkout.svc.cluster.local:5050
  AD_SERVICE_ADDR: adservice.ad.svc.cluster.local:9555

  ENABLE_PROFILER: "0"
  ENABLE_TRACING: "0"
