apiVersion: v1
kind: Service
metadata:
  name: checkoutservice
  namespace: checkout
spec:
  type: ClusterIP
  selector:
    app: checkoutservice
  ports:
    - name: grpc
      port: 5050
      targetPort: 5050
