apiVersion: v1
kind: Service
metadata:
  name: shoppingassistantservice
  namespace: shoppingassistant
spec:
  type: ClusterIP
  selector:
    app: shoppingassistantservice
  ports:
    - name: http
      port: 8080
      targetPort: 8080
